ddd_ej00:
	ddd --debugger gdb-multiarch tp_01_00/obj/ej_sumaabi.elf
ddd_ej01:
	ddd --debugger gdb-multiarch tp_01_01/obj/ej_memcopy.elf
ddd_ej02:
	ddd --debugger gdb-multiarch tp_01_02/obj/ej_irq.elf
ddd_ej03:
	ddd --debugger gdb-multiarch tp_01_03/obj/ej_timer.elf
ddd_ej04:
	ddd --debugger gdb-multiarch tp_01_04/obj/ej_paging.elf
ddd_ej05:
	ddd --debugger gdb-multiarch tp_01_05/obj/ej_scheduler.elf